server:
  port: 8082

spring:
  application:
    name: mall-demo
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall
    password: 123456
  redis:
    host: 192.168.1.118 # Redis服务器地址
    database: 5 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 300ms # 连接超时时间（毫秒）
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false #开发时关闭缓存,不然没法看到实时页面
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug

host:
  mall:
   admin: http://localhost:8080
